BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "SmallCells" (
	"eNB"	INTEGER NOT NULL,
	"MCCMNC"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "Points" (
	"Latitude"	NUMERIC NOT NULL,
	"Longitude"	NUMERIC NOT NULL,
	"MCC"	NUMERIC NOT NULL,
	"MNC"	NUMERIC NOT NULL,
	"TAMeters"	NUMERIC NOT NULL,
	"CellID"	INTEGER NOT NULL,
	"System"	TEXT NOT NULL DEFAULT 'LTE',
	"Band"	INTEGER NOT NULL,
	"ARFCN"	INTEGER NOT NULL,
	"Signal"	NUMERIC NOT NULL
);
COMMIT;
